---

language: python

python:
  - "2.7"

sudo: false

before_install:
  - apt-get update -qq
  - apt-get install git
  - git clone https://github.com/ktbyers/netmiko.git
  - cd netmiko
  - python setup.py install
  - pip install -r requirements.txt
  - cd ..

install:
  - pip install ansible
  - pip install gtextfsm

script:
  - python test-templates.py
