---

language: python

python:
  - "2.7"

sudo: false

before_install:
  # - sudo apt-get update -qq
  #- apt-get install git
  - git clone https://github.com/ktbyers/netmiko.git
  - cd netmiko
  - python setup.py install
  - pip install -r requirements.txt
  - cd ..
  - pip install --upgrade pip
  - pip install gtextfsm
  - which python

install:
  - pip install ansible

script:
  - sudo python test-templates.py
