---

language: python

python:
  - "2.7"

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git
  - git clone https://github.com/ktbyers/netmiko.git
  - cd netmiko
  - python setup.py install
  - pip install -r requirements.txt
  - cd ..
  - pip install --upgrade pip
  - pip install gtextfsm
  - which python
  - locate gtextfsm

install:
  - pip install ansible

script:
  - python test-templates.py
