---

- name: Verify TextFSM template
  hosts: localhost
  gather_facts: False

  vars_prompt:
    - name: template_name
      prompt: "Enter the name of the template to verify"
      default: "cisco_show_ip_int_brief"
      private: no

  tasks:
  
  - name: extract vendor name from template name
    set_fact: vendor="{{ template_name | split("_") | first }}"

  - name: extract command from template name
    set_fact: command_variable="{{ template_name | split(vendor + "_") | last }}"

  - name: extract command string from command_variable
    set_fact: command="{{ command_variable | split("_") | join(" ") }}"

  - name: run TextFSM locally on test input
    ntc_show_command:
      connection: offline
      file: "{{ item }}"
      vendor: "{{ vendor }}"
      command: "{{ command }}"
    with_fileglob:
      - "{{ TEST_DIR }}/{{ vendor }}/{{ template_name}}*.raw"
    register: ntc_result
  - debug: var="{{ntc_result.results}}"  
  - name: read parsed sample files
    include_vars: "{{ item.item | split('.') | first }}.parsed"
    with_items: "{{ ntc_result.results }}" 
    register: ntc_result 

  - name: verify that parsed result is the same as expected
    compare_dict:
      result: "{{ item.item.response }}"
      sample: "{{ item.ansible_facts.parsed_sample }}"
    with_items: "{{ ntc_result.results }}"
