---

- name: extract vendor name from template name
  set_fact: vendor="{{ template_name | split("_") | first }}"

- name: extract command from template name
  set_fact: command_variable="{{ template_name | split(vendor + "_") | last }}"

- name: extract command string from command_variable
  set_fact: command="{{ command_variable | split("_") | join(" ") }}"
 
- name: read vendor environment settings
  include_vars: "{{ TEST_DIR }}/{{ vendor }}.yml"

- name: read parsed output sample
  include_vars: "{{ TEST_DIR }}/{{ vendor }}/{{ command_variable }}/{{ template_name }}.parsed"

- name: update raw variable path
  set_fact: raw="{{ TEST_DIR }}/{{ vendor }}/{{ command_variable }}/{{ template_name }}.raw"
