---

- name: GET VLANS IN REAL TIME
  ntc_show_command:
    connection: "{{ connection }}"
    file: "{{ raw }}"
    vendor: "{{ vendor }}"
    device_type: "{{ device_type }}"
    command: "{{ command }}"
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: vlans

